### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by viseshrp** [LuckyTurtleDev/docker-images#10]
Hi @LuckyTurtleDev 
Firstly, thanks very much for this image. I am trying to run it on my raspberry pi and plan to expose it to the internet.

Do you know what I should add to mention the base URL (eg: http://anki.mysite.com:8080)?

```
version: '3.3'
services:
    anki:
        image: ghcr.io/luckyturtledev/anki
        container_name: anki
        environment:
            - SYNC_USER1=user:pass
            - RUST_LOG=info
        ports:
         - 127.0.0.1:10080:8080
        volumes:
            - './data:/data'
        user: 1000:1000
        restart: unless-stopped
```
